import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

import { publicEnv } from '@/lib/env/public'
import '@/styles/globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

// Ler `publicEnv` aqui valida as variáveis NEXT_PUBLIC_* no build (o layout é
// pré-renderizado). Título, descrição e Open Graph completos entram em T10.
export const metadata: Metadata = {
  metadataBase: new URL(publicEnv.NEXT_PUBLIC_SITE_URL),
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: LayoutProps<'/'>) {
  return (
    <html lang="pt-BR" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  )
}
